busybox: &busybox #YAML anchor
  type: registry-image
  source: 
    repository: busybox

jobs:
- name: the-job
  plan:
  - task: create-one-output
    # The task config has the artifact `the-output`
    # output_mapping will rename `the-output` to `demo-disk`
    # in the rest of the job's plan
    output_mapping:
      the-output: demo-disk
    config:
      platform: linux
      image_resource: *busybox
      outputs:
        - name: the-output
      run:
        path: /bin/sh
        args:
          - -cx
          - |
            ls -lah ./the-output/
            date > ./the-output/file
  # this task expects the artifact `demo-disk` so no mapping is needed
  - task: read-ouput-from-previous-step
    config:
      platform: linux
      image_resource: *busybox
      inputs:
        - name: demo-disk
      outputs:
        - name: demo-disk
      run:
        path: /bin/sh
        args:
          - -cx
          - |
            date > ./demo-disk/file2
            ls -lah ./demo-disk/
            cat ./demo-disk/file
  - task: rename-and-read-output
    # This task expects the artifact `generic-input`.
    # input_mapping will map the task's `generic-input` to
    # the job plans `demo-disk` artifact.
    # `demo-disk` is renamed to `generic-input`.
    input_mapping:
      generic-input: demo-disk
    config:
      platform: linux
      image_resource: *busybox
      inputs:
        - name: generic-input
      run:
        path: /bin/sh
        args:
          - -cx
          - |
            date > ./generic-input/file3
            ls -lah ./generic-input/
            cat ./generic-input/file
  - task: try-to-read-the-output
    input_mapping:
      generic-input: the-output
    config:
      platform: linux
      image_resource: *busybox
      # `the-output` is not available in the job plan
      # so this task will error while initializing
      # since there's no artiact named `the-output` in
      # the job's plan
      inputs:
        - name: generic-input
      run:
        path: /bin/sh
        args:
          - -cx
          - |
            date > ./generic-input/file4
            ls -lah ./generic-input/
            cat ./generic-input/file