var_sources:
- name: vault
  type: vault
  config:
    url: http://18.185.31.216:8200
    client_token: s.A9AwQePysA9ks6MGypeb1nTC
    path_prefix: /secret/
resources:
- name: concourse-examples
  type: git
  icon: github
  source:
    uri: https://github.com/OlegYarmolenko/examples
resources:
- name: repo
  type: git
  source:
    uri: git@github.com:OlegYarmolenko/examples.git
    branch: master
    private_key: ((vault:hpg5/windows.p_key))
jobs:
- name: read-the-readme
  plan:
  - get: repo
  - task: cat-readme
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs: # pass concourse-examples into this task step
      - name: repo
      run:
        path: cat
        args: ["repo/README.md"]
